# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'wanderwise' do
pod 'AFNetworking'
pod 'CocoaAsyncSocket'
end

target 'wanderwiseTests' do

end

